"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/footer/Footer";
import store from "@/components/store/store";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "User Listing",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Navbar />

          <main>{children}</main>

          <Footer />
        </Provider>
      </body>
    </html>
  );
}
